### ISSUE TITLE
Don't allow switching to the currently selected if it is not a smos file

### ISSUE THREAD

**Issue by NorfairKing** [NorfairKing/smos#142]
When you press `Esc` in the filebrowser it goes to an empty file screen if a directory was selected.
Instead, nothing should happen.

**Comment by cgeorgii** [comment]
Hey @NorfairKing I'm currently learning Haskell and (as you surely noticed) this project really interests me. I am willing to help since I think the tool can be very valuable.

If you're willing to point me in the right direction, I would love to give this issue a shot, since I came across the problem very early in my exploration and it is a show stopper.

**Comment by NorfairKing** [comment]
Hi @cgeorgii  That sounds great!

> If you're willing to point me in the right direction, I would love to give this issue a shot

Sure!
This may not be the best issue to start if you're new at Haskell but I'll show you exactly where the issue is: 

This is the function that determines which file is selected: 
https://github.com/NorfairKing/smos/blob/master/smos-cursor/src/Smos/Cursor/FileBrowser.hs#L72-L75

This is where the entering actually happens:
https://github.com/NorfairKing/smos/blob/master/smos/src/Smos/Actions/Browser.hs#L98-L103

This is what we should use instead of `switchToFile`:
https://github.com/NorfairKing/smos/blob/0611e727e4690ff6099b5b277750c430284fc0a3/smos/src/Smos/Actions/File.hs#L48

And these two are what you need to make a `SmosFileCursor`:
https://github.com/NorfairKing/smos/blob/0611e727e4690ff6099b5b277750c430284fc0a3/smos-cursor/src/Smos/Cursor/SmosFile.hs#L92
and
https://github.com/NorfairKing/smos/blob/0611e727e4690ff6099b5b277750c430284fc0a3/smos-data/src/Smos/Data.hs#L48


> since I came across the problem very early in my exploration and it is a show stopper.

This seems strange to me. Could you explain how that is a show stopper?

**Comment by cgeorgii** [comment]
> This seems strange to me. Could you explain how that is a show stopper?

Well, let's go step by step on what happens to me and you can let me know if this is not related to the issue:

1. I start smos from the CLI using the `smos` executable and see this screen:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/12649588/91173159-a9d9b700-e6dd-11ea-9c2e-61b603ade280.png">

2. I open the browser for projects/archived items with `ba` or `bp` and since I don't have any projects or files in here, I see the following screen:

<img width="608" alt="image" src="https://user-images.githubusercontent.com/12649588/91172935-4c456a80-e6dd-11ea-84ce-3efd22fd716b.png">

3. If I press `ESC` on this screen, I fall on the following screen and, no matter what I do, I can't leave. Quitting doesn't work, help doesn't work, nothing works:
<img width="679" alt="image" src="https://user-images.githubusercontent.com/12649588/91173056-7c8d0900-e6dd-11ea-840a-6b0ffdc59561.png">

4. The only possible action at this point is to restart the terminal.

At this point I wanted to create an issue here on Github but searched first and this one seems to describe the same problem. Let me know if this is a different issue.

**Comment by NorfairKing** [comment]
Ah! That's a different problem entirely so let's create a separate issue about it.
~~By the way you can still press `q` to exit smos from here.~~ Maybe we should mention that on the empty page. That's definitely something you could do as a beginner.

**Comment by NorfairKing** [comment]
I just quick-fixed this on development so that you don't get stuck anymore, but Ideally you should never get into this situation where no file is opened at all. So please still open an issue.

**Comment by cgeorgii** [comment]
Issue opened [here](https://github.com/NorfairKing/smos/issues/150) and fix verified on the `development` branch. Thanks ;)
