### ISSUE TITLE
LineWrap around

### ISSUE THREAD

**Issue by mezeguer** [NorfairKing/smos#224]
Right now, when writing a very long description of an entry there is no line-wrapping behaviour. This generates that very long lines simply disappear from view.

**Comment by NorfairKing** [comment]
I'd love to figure this out. Unfortunately we have the following problem:

Let's say you have a piece of contents with three lines:
```
this is the first line
this is the second line which is way too long because reasons
this is the third line.
```

You might want to wrap it to look like this:

```
this is the first line             |
this is the second line which      |
is way too long because reasons    |  <- end of screen
this is the third line.            |
```

That's fine. So far it's doable.

The problem comes when you now want to edit these contents: Where do you put the blink-y box?
The part of the code that decides where to put the blink-y-box (coordinates: `(line number, characters before)`) has no idea how:

1. The previous lines were wrapped and
2. How the current line is wrapped
3. How wide the screen even is.

Maybe the author of brick: @jtdaugherty has run into this problem before and could advise?

**Comment by jtdaugherty** [comment]
@NorfairKing Can you give me a bit more context? Is this in the context of a Brick built-in editor? Are you wanting to know whether it's possible to do wrapping in that editor?

**Comment by NorfairKing** [comment]
Hi @jtdaugherty! Super cool that you responded.

This is not about the `Brick.Widgets.Edit` but if you've solved it there, that would be great and I could probably learn from that solution. Have you solved line wrapping there?

The question is "how do you do text wrapping in an editor for that text?".

In this context we're using a [`Cursor.TextField.TextFieldCursor`](https://hackage.haskell.org/package/cursor-0.3.0.0/docs/Cursor-TextField.html#t:TextFieldCursor) but it's very similar to the `TextZipper` that brick uses (I think).

**Comment by jtdaugherty** [comment]
The Brick editor doesn't deal with this problem at all; in fact, it explicitly requires that however you render the text does *not* change the text layout relative to what the underlying zipper contains. That means that if the editor contains five lines of text, then the rendered version's structure must match that exactly. That basically means that all you can do in an editor's rendering function is change attributes, not layout.

The fundamental reason why the Brick editor has this requirement is because the cursor position is part of the *editor state*. Consequently, if the cursor position were to need to change *at rendering time* because of a decision to wrap lines of text *at render time*, that would make the cursor position at rendering time different than what is in the state. That furthermore means that if the user sees one thing and the state says another, then cursor movement relative to what they *see* would not agree with cursor movement relative to what the state says.

The reason the Brick editor works this way is because it assumes that any "destructive" changes to the text (such as wrapping) are done *at event handling time* rather than rendering time. That makes rendering straightforward, and it pushes the complexity of determining how and when to wrap lines of text into an event handler. So to make this work in a Brick editor, someone would need to write an event handler that took care of wrapping lines of text *in the editor state* and transforming the cursor position there at the time of the event. At that point, the job of rendering is just a matter of drawing what the state reports.

The challenge of writing an event handler like this isn't too great, because you can find out (in an event handler) how big your editor appears on the screen by checking for its extent in the Brick `EventM` monad. There are some caveats to that, but basically, that's what you'd need to do. You'd need to track 1) what lines of text are in your editor, 2) how big the viewed editor area is (its extent), 3) which lines *appear* to be wrapped even if they do not physically contain line breaks, and 4) where the cursor is placed logically within that text, so you can figure out how to translate that logical cursor position to a physical one at rendering time.

**Comment by jtdaugherty** [comment]
I should note that this approach differs from what you'd do if you just used the built-in Brick line-wrapping functions, because those are only useful for render-time wrapping. That's fine if you don't need the results of those wrapping decisions to feed back into application behavior, but it doesn't work so well for things like this where application decisions made in event handlers need to be based on wrapping decisions.

**Comment by NorfairKing** [comment]
@jtdaugherty Thanks for the very detailed response. I only just realised that I'd not responded to it, my appologies. It sounds like this would be a very significant refactor that I cannot justify spending time on at the moment.
