### ISSUE TITLE
Working with file attachments

### ISSUE THREAD

**Issue by cipharius** [NorfairKing/smos#69]
Usually when working with text oriented task/note manager apps it's awkward to associate tasks or projects with external attachments.

I want to start a discussion about potential and existing workflows for working with attachments in smos.

First thing that comes up in mind is storing URIs to online and offline resources as properties. Another alternative would be storing them as references in subentry.

**Comment by NorfairKing** [comment]
Usually I put everything related to a task in the contents of the entry.
So press `<Enter><Enter>` to run `entrySelectContents` and then put an URI there.

Does that work for your use-case? Is there something you'd like to do that you can't? Is there a certain type of UX that you have in mind?

**Comment by cipharius** [comment]
For daily usage, I'd probably want some sort of integration with desktop environment.
Say, an action for opening URI under cursor with system's default file opener.

As for files, it would probably make most sense to have project related files stored in per project directory, so in that case, I'd want to be able to quickly open this directory with file browser.

How do you personally manage new smos file creation? Do you create them manually or you have some automation for that? I'm currently bit stuck on figuring out when to use smos TUI, when to rely on other tools and how to cross the boundary between them.

Most important UX aspect for me would be the ability to manipulate resource references using only keyboard bindings. That includes inserting links and opening them.

**Comment by NorfairKing** [comment]
@cipharius I personally don't use any fanciness.

> For daily usage, I'd probably want some sort of integration with desktop environment.
> Say, an action for opening URI under cursor with system's default file opener.

That seems doable.
We'd have to make something aware of the concept of attachments.
I think adding a new piece to the concept of `Entry` would make sense for that.
Alternatively we could do it with properties, but I'm not sure if it's a good idea to conflate those two.
Also: Your terminal probably supports clicking on links if you have a link in the text of your terminal.

> As for files, it would probably make most sense to have project related files stored in per project directory, so in that case, I'd want to be able to quickly open this directory with file browser.

Right! Currently you can already use `bp` to open the projects directory with the smos file browser.
Opening the current directory is not supported yet until we can do lazy uncollapsing of directories.
Otherwise opening the home dir would basically never finish depending on your home dir.

> How do you personally manage new smos file creation? Do you create them manually or you have some automation for that? I'm currently bit stuck on figuring out when to use smos TUI, when to rely on other tools and how to cross the boundary between them.

I use `smos ~/workflow/projects/new-file.smos` with some aliases.
There's no support for opening new files from the smos file browser yet. See https://github.com/NorfairKing/smos/issues/63.

> Most important UX aspect for me would be the ability to manipulate resource references using only keyboard bindings. That includes inserting links and opening them.

This will take some thinking because I wouldn't use this personally, I think.
I currently store reference files for tasks in the `workflow/reference` dir using some aliases to open those.

Thanks for opening up the discussion.
If you're willing to help out, I think we could scope out the necessary work together.

**Comment by cipharius** [comment]
I would be interested in contributing, but I want to get the hang of smos as it currently is.

I wasn't aware of the CLI usage of smos for opening/creating files. Will read the reference for that interface!

**Comment by NorfairKing** [comment]
Super! Please open an issue if you think something is missing from the docs.

**Comment by NorfairKing** [comment]
Now I remember why I didn't build this from the start: these links can break. We'll have to think carefully about how to do this well, if we do it.
