### ISSUE TITLE
Allow overwriting existing keybindings

### ISSUE THREAD

**Issue by cipharius** [NorfairKing/smos#71]
When an action is bound to an existing binding, the default action is persisted.

It works with the reset option enabled, but it would be nicer to allow overwritting  existing bindings.

**Comment by cipharius** [comment]
I actually would like to solve this one myself, seems like a good first issue.

**Comment by NorfairKing** [comment]
@cipharius Sounds great! 
This will touch a fair bit of code, but all within the `smos` package.
How would you like the configuration format for that to look?
This is the current schema:

```
keys: # optional
  # Keybindings
  # KeybindingsConfiguration
  reset: # optional
    # Whether to reset all keybindings. Set this to false to add keys, set this to true to replace keys.
    <boolean>
  subcontext: # optional
    # FileKeyConfigs
    subsubcontext: # optional
      - # KeyConfig
        key: # required
          # The key to match
          <string>
        action: # required
          # The name of the action to perform when the key is matched
          <string>
```

I'm hoping you have a better idea, but here is the first thing I came up with:

Rename `reset` to `reset-all`
Within any `subsubcontext`, have two keys: `bindings` and `resets`:

```
subsubcontext:
  bindings:
      - # Keybindings for when the file is empty
        # KeyConfig
        key: # required
          # The key to match
          <string>
        action: # required
          # The name of the action to perform when the key is matched
          <string>
  resets:
      - # Action names of actions to reset within this subsubcontext.
        <string>
```

It's not backward compatible, but that's not a big deal at this point (because we have excellent docs now thanks to `yamlparse-applicative`).

**Comment by NorfairKing** [comment]
Alternative idea: Treat any configured keybinding as an overwrite for that action name.
If you then want the action bound to two keys, you just use two configured bindings.

I think I ilke this better.

For the record, we want all of these things to be possible::

- Add a binding for an action that hasn't been bound yet
- Add a binding for an action that has been bound already, without removing the old binding
- Overwrite a binding for an action that has been bound already, and also remove the other bindings that that action has.
- Overwrite a binding for an action that has been bound already, but don't remove the other bindings that that action has.

This should all happen on the subsubcontext granularity. Because actions can be bound differently per subsubcontext.

**Comment by cipharius** [comment]
The second approach is what I had in mind. Basically, if the key is mapped to action in configuration, user expects it to work no questions asked.

Overwriting default binding shouldn't be an issue. Only thing left to resolve is what happens when user binds same keys in same context to two actions. Should the repeated key binding be silently ignored or should smos raise an error at startup? Perhaps this is something to solve seperately.

**Comment by cipharius** [comment]
I see that you use actions bound to keys model. Any particular reason for this decision?

What about storing Key -> Action(s) mappings for each context? That should be a faster and simpler way to find the matching actions. Although looking at the code, it would require some different approach for key sequence mapping and would touch quite a lot of code.

**Comment by NorfairKing** [comment]
> Should the repeated key binding be silently ignored or should smos raise an error at startup? Perhaps this is something to solve seperately.

We should make an issue about keybinding conflicts. I think smos will currently just arbitrarily use one of them to activate (but still always the same one).

> What about storing Key -> Action(s) mappings for each context? 

1. You'd have to use a map and not a function, because of the automatic `help` screen.
2. Actions are not activated by keys but by key combinations.
3. Actions are not necessarily activated by predetermined key combinations, because there are also `ActionWith Char` actions that you need for inserting characters.

If you're interested in overhauling this mechanism, then we need to make sure that these stay possible:

- Press one key, have an `Action` fired.
- Press a character key, have an `ActionWith Char` fired.
- Press a key sequence, have an `Action` fired.
- Press a key sequence that ends in a character key, have an `ActionWith Char` fired.
- Press a key sequence that ends in `x`, have the corresponding action fired instead of the action for just pressing `x`.

> Although looking at the code, it would require some different approach for key sequence mapping and would touch quite a lot of code.

I agree, and I'm not convinced that it would be simpler.

**Comment by NorfairKing** [comment]
I made https://github.com/NorfairKing/smos/issues/72 for the conflicts.

**Comment by NorfairKing** [comment]
Shorter explanation: such a map wouldn't get you any simplicity because one keystroke can potentially activate an arbitrarily long sequence of keys in a binding, so you can't use a lookup anyway.

**Comment by cipharius** [comment]
Alright, I see where the complexity comes from. Will think about the key mapping in meanwhile and take a look at how kakoune, emacs Evil and spacemacs approaches complex sequences of modal bindings.

For now will deal with this particular issue.

**Comment by NorfairKing** [comment]
> Will think about the key mapping in meanwhile and take a look at how kakoune, emacs Evil and spacemacs approaches complex sequences of modal bindings.

That's a great idea! I haven't looked at their code yet. If you find any article or docs about it, please let me know.

**Comment by cipharius** [comment]
Just found out why I couldn't overwrite the existing keybindings, I hadn't noticed that `contents` mappings are nested under `file` mappings. 

That brings up another issue, smos accepts incorrectly structured configuration.

I'll mark this issue as closed, since keybindings in config do seem to take precedence over defaults.

P.S At least managed to set up development environment for smos and got ghci debugger working with the project

**Comment by NorfairKing** [comment]
@cipharius It's good that you got your problem solved, but the actual issue of overwriting within a subsubcontext still exists so feel free to re-open this issue as necessary.
Also please let me know if I should add any docs based on a misunderstanding you may have had.

**Comment by cipharius** [comment]
Alright, will reopen.

As for my issue, it would have helped to get some error message about misconfigured config.

Example of config I had tried to use:

```yaml
keys:
  reset: false
  contents:
    - key: M-l
      action: contentsMoveRight
```

This got interpreted silently, yet nothing happened.

Later I noticed that `contents` have to be defined under `file` context.
```

**Comment by NorfairKing** [comment]
@cipharius Aha! I'm afraid this is not possible with https://hackage.haskell.org/package/yaml as-is. Hopefully the reference docs here https://smos.cs-syd.eu/smos can help.
